"""Per-replicate ladder profiles of the fiducial band (Rust-accelerated).

Study infrastructure for the offline calibration of the fiducial band's trim
exponent (``stats/c_calibration_spec.md``). For one replicate — one merged
label sequence — the ``fiducial_core.fiducial_ladder_profile`` kernel draws
the fiducial cloud once and returns, for every trim depth ``j`` on a
caller-supplied ladder, whether the allowance-augmented band at depth ``j``
covers a reference curve (the Clopper-Pearson upper allowance evaluated at
that depth's own local level ``j / (M + 1)``), together with band areas,
miss diagnostics, the draw-depth distribution, the reference curve's own
tie-inclusive depth, and the same statistics at "reference-map" depths
selected exactly the way production selects them (the ``alpha_eff``-quantile
of the draw depths, clamped to ``[1, M / 2]``).

The cloud is generated by the same draw-indexed RNG as the production tube
kernel, so a given seed yields bit-identical draws to
:func:`studroc_paper.methods.fiducial_band_rs.fiducial_band_rs`, and only
O(J + M) summaries cross the FFI boundary — the M x K cloud never does.
Depths are computed over the production thinned trim-grid by default
(:func:`studroc_paper.methods.fiducial_band.production_trim_rows`).
"""

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

from .fiducial_band import production_trim_rows
from .fiducial_band_rs import _require_fiducial_core


def make_ladder(n_draws: int) -> NDArray[np.int64]:
    """Trim-depth ladder for profiling: dense small depths, geometric above.

    Every depth 1-40 plus ~70 geometrically spaced depths up to
    ``n_draws // 2``, deduplicated. Matches the harness convention of
    ``stats/experiments/m2_experiments.py``.

    Args:
        n_draws: Monte Carlo cloud size ``M``.

    Returns:
        Strictly increasing int64 array of depths in ``[1, max(M // 2, 1)]``.
    """
    half = max(n_draws // 2, 1)
    lo = np.arange(1, min(41, half + 1))
    hi = np.unique(np.rint(np.geomspace(max(len(lo), 1), half, 70)))
    ladder = np.unique(np.concatenate([lo, hi])).astype(np.int64)
    return ladder[(ladder >= 1) & (ladder <= half)]


def khat_from_labels(lab_s: NDArray) -> NDArray[np.int64]:
    """Empirical TPR counts on the native grid from the merged label sequence.

    ``khat[i]`` = number of positives ranked above the ``(i+1)``-th ranked
    negative (staircase-upper convention); ``khat[n0] = n1``.

    Args:
        lab_s: Merged 0/1 label sequence in rank order (ascending placement
            value = descending score).

    Returns:
        Int64 array of length ``n0 + 1``.
    """
    lab_s = np.asarray(lab_s).astype(np.int64)
    n1 = int(lab_s.sum())
    cpos = np.cumsum(lab_s)
    neg_idx = np.flatnonzero(lab_s == 0)
    return np.concatenate([cpos[neg_idx], [n1]]).astype(np.int64)


@dataclass(frozen=True)
class LadderProfile:
    """Full ladder profile of one replicate.

    Attributes:
        ladder: The profiled trim depths (strictly increasing).
        covered: Per ladder depth, whether the allowance-augmented band
            covers the reference curve everywhere.
        viol_low: Per ladder depth, whether the reference dips below the
            lower edge somewhere.
        viol_high: Per ladder depth, whether the reference exceeds the upper
            edge somewhere.
        miss_depth: Per ladder depth, the largest violation (0 if covered).
        worst_k: Per ladder depth, grid index of the first largest
            violation (-1 if covered).
        area: Per ladder depth, mean band width with allowances applied.
        area_raw: Per ladder depth, mean width of the raw tube.
        alpha_effs: The effective levels the reference-map depths were
            selected at.
        ref_j: Realized production trim depth per effective level.
        ref_covered: Coverage indicator per effective level.
        ref_viol_low: Lower-violation indicator per effective level.
        ref_viol_high: Upper-violation indicator per effective level.
        ref_miss_depth: Largest violation per effective level.
        ref_worst_k: Violation grid index per effective level.
        ref_area: Mean allowance-augmented band width per effective level.
        ref_area_raw: Mean raw-tube width per effective level.
        depths_sorted: Sorted min-p depths of all draws over the trim rows.
        truth_depth_low: Reference curve's minimum tie-inclusive rank from
            below over all grid columns.
        truth_depth_high: Reference curve's minimum tie-inclusive rank from
            above over all grid columns.
        edges: ``(depths, lower, upper)`` raw tube edges at every evaluated
            depth (rows of shape ``(len(depths), n0 + 1)``), or ``None``.
    """

    ladder: NDArray[np.int64]
    covered: NDArray[np.bool_]
    viol_low: NDArray[np.bool_]
    viol_high: NDArray[np.bool_]
    miss_depth: NDArray[np.float64]
    worst_k: NDArray[np.int64]
    area: NDArray[np.float64]
    area_raw: NDArray[np.float64]
    alpha_effs: NDArray[np.float64]
    ref_j: NDArray[np.int64]
    ref_covered: NDArray[np.bool_]
    ref_viol_low: NDArray[np.bool_]
    ref_viol_high: NDArray[np.bool_]
    ref_miss_depth: NDArray[np.float64]
    ref_worst_k: NDArray[np.int64]
    ref_area: NDArray[np.float64]
    ref_area_raw: NDArray[np.float64]
    depths_sorted: NDArray[np.uint32]
    truth_depth_low: int
    truth_depth_high: int
    edges: tuple[NDArray, NDArray, NDArray] | None

    def depth_cdf_at(self, depths: NDArray) -> NDArray[np.int64]:
        """Number of draws with min-p depth strictly below each given depth.

        Args:
            depths: Depths at which to evaluate the draw-depth CDF.

        Returns:
            Int64 counts, one per requested depth.
        """
        return np.searchsorted(
            self.depths_sorted, np.asarray(depths), side="left"
        ).astype(np.int64)


def ladder_profile(
    lab_s: NDArray,
    *,
    rtrue: NDArray,
    n_draws: int,
    seed: int,
    ladder: NDArray | None = None,
    alpha_effs: NDArray | tuple[float, ...] = (),
    trim_rows: NDArray | str | None = "production",
    return_edges: bool = False,
    n_threads: int = 0,
) -> LadderProfile:
    """Compute the full ladder profile of one replicate via the Rust kernel.

    Args:
        lab_s: Merged 0/1 label sequence in rank order (0 = negative,
            1 = positive), ties already broken.
        rtrue: Reference (true) curve evaluated on the native grid
            ``t_k = k / n0`` — ``n0 + 1`` values in ``[0, 1]``.
        n_draws: Monte Carlo cloud size ``M``.
        seed: RNG seed for the fiducial draws. The same seed yields
            bit-identical draws to the production tube kernel.
        ladder: Trim depths to profile; ``None`` uses
            :func:`make_ladder`.
        alpha_effs: Effective levels at which to evaluate the production
            depth-selection rule (the reference maps).
        trim_rows: Grid rows for the min-p depth pass. ``"production"``
            (default) applies :func:`production_trim_rows`; ``None`` uses
            the full grid; an array gives explicit rows.
        return_edges: Also return the raw tube edges at every evaluated
            depth (large: ``O(n_depths * n0)`` floats).
        n_threads: Rayon thread count; 0 uses the global pool.

    Returns:
        A :class:`LadderProfile`.

    Raises:
        ImportError: If the ``fiducial_core`` extension is not built.
        ValueError: If any input is malformed (propagated from the kernel).
    """
    core = _require_fiducial_core()

    lab_s = np.ascontiguousarray(np.asarray(lab_s), dtype=np.uint8)
    n1 = int(lab_s.sum())
    n0 = len(lab_s) - n1
    n_grid = n0 + 1
    rtrue = np.ascontiguousarray(np.asarray(rtrue), dtype=np.float64)
    if len(rtrue) != n_grid:
        raise ValueError(f"rtrue must have n0 + 1 = {n_grid} entries, got {len(rtrue)}")

    if ladder is None:
        ladder = make_ladder(n_draws)
    ladder = np.ascontiguousarray(np.asarray(ladder), dtype=np.uint32)
    alpha_effs = np.ascontiguousarray(np.asarray(alpha_effs), dtype=np.float64)

    if isinstance(trim_rows, str):
        if trim_rows != "production":
            raise ValueError(f"Unknown trim_rows mode: {trim_rows!r}")
        trim_rows = production_trim_rows(n_grid)
    trim_arg = (
        None
        if trim_rows is None
        else np.ascontiguousarray(np.asarray(trim_rows), dtype=np.uint64)
    )

    khat = khat_from_labels(lab_s)
    out = core.fiducial_ladder_profile(
        lab_s,
        n_draws,
        int(seed),
        rtrue,
        khat.astype(np.uint32),
        ladder,
        alpha_effs,
        trim_arg,
        return_edges,
        n_threads,
    )

    edges = None
    if return_edges:
        depths = np.asarray(out["edge_depths"])
        edges = (
            depths,
            np.asarray(out["edge_lower"]).reshape(len(depths), n_grid),
            np.asarray(out["edge_upper"]).reshape(len(depths), n_grid),
        )
    return LadderProfile(
        ladder=ladder.astype(np.int64),
        covered=np.asarray(out["ladder_covered"]),
        viol_low=np.asarray(out["ladder_viol_low"]),
        viol_high=np.asarray(out["ladder_viol_high"]),
        miss_depth=np.asarray(out["ladder_miss_depth"]),
        worst_k=np.asarray(out["ladder_worst_k"]),
        area=np.asarray(out["ladder_area"]),
        area_raw=np.asarray(out["ladder_area_raw"]),
        alpha_effs=alpha_effs,
        ref_j=np.asarray(out["ref_j"]).astype(np.int64),
        ref_covered=np.asarray(out["ref_covered"]),
        ref_viol_low=np.asarray(out["ref_viol_low"]),
        ref_viol_high=np.asarray(out["ref_viol_high"]),
        ref_miss_depth=np.asarray(out["ref_miss_depth"]),
        ref_worst_k=np.asarray(out["ref_worst_k"]),
        ref_area=np.asarray(out["ref_area"]),
        ref_area_raw=np.asarray(out["ref_area_raw"]),
        depths_sorted=np.asarray(out["depths_sorted"]),
        truth_depth_low=int(out["truth_depth_low"]),
        truth_depth_high=int(out["truth_depth_high"]),
        edges=edges,
    )
