"""Data generation utilities for ROC confidence band simulations."""

from .roc_to_dgp import (
    BetaOpposingSolver,
    BimodalNegativeSolver,
    LHSSample,
    StudentTSolver,
    generate_simulation_design,
    map_lhs_to_dgp,
)
from .true_rocs import (
    DGP,
    estimate_true_roc,
    get_standard_test_dgps,
    make_beta_opposing_skew_dgp,
    make_beta_same_support_opposing_dgp,
    make_bimodal_both_dgp,
    make_bimodal_negative_dgp,
    make_cauchy_dgp,
    make_exponential_dgp,
    make_gamma_dgp,
    make_gaussian_dgp,
    make_gaussian_mixture_dgp,
    make_heteroskedastic_gaussian_dgp,
    make_logitnormal_dgp,
    make_lognormal_dgp,
    make_pareto_dgp,
    make_student_t_dgp,
    make_uniform_dgp,
    make_uniform_full_overlap_dgp,
    make_uniform_no_overlap_dgp,
    make_uniform_partial_overlap_dgp,
    make_weibull_dgp,
    visualize_dgp,
)

__all__ = [
    "BetaOpposingSolver",
    "BimodalNegativeSolver",
    "DGP",
    "LHSSample",
    "StudentTSolver",
    "estimate_true_roc",
    "generate_simulation_design",
    "get_standard_test_dgps",
    "make_beta_opposing_skew_dgp",
    "make_beta_same_support_opposing_dgp",
    "make_bimodal_both_dgp",
    "make_bimodal_negative_dgp",
    "make_cauchy_dgp",
    "make_exponential_dgp",
    "make_gamma_dgp",
    "make_gaussian_dgp",
    "make_gaussian_mixture_dgp",
    "make_heteroskedastic_gaussian_dgp",
    "make_logitnormal_dgp",
    "make_lognormal_dgp",
    "make_pareto_dgp",
    "make_student_t_dgp",
    "make_uniform_dgp",
    "make_uniform_full_overlap_dgp",
    "make_uniform_no_overlap_dgp",
    "make_uniform_partial_overlap_dgp",
    "make_weibull_dgp",
    "map_lhs_to_dgp",
    "visualize_dgp",
]
